import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:feedbackkit_flutter/src/models/comment.dart';

/// `QA-UNIT04-COMMENTS` `-13` — the Flutter SDK decodes the payload the server actually
/// sends.
///
/// The corpus in `test/fixtures/comment-wire-corpus.json` is **not** written here. It is
/// generated by the server's `CommentWireContractTests` from the server's own
/// `CommentResponseDTO` through the server's own configured encoder, and that suite
/// byte-diffs this committed copy against a fresh regeneration.
///
/// ✅ **GREEN SINCE 2026-08-15** — these cases were authored red on arrival against two
/// shipped defects, and `QA-UNIT10-SDK-PARITY` landed the routed fixes that flipped them:
///
///  - `isTeamMember` read `is_team_member` / `isTeamMember`, neither of which the server
///    sends, so it silently resolved `false` and the admin badge never rendered. It now
///    reads the server's actual key, `is_admin`.
///  - `feedbackId` read `feedback_id`, which the server never sends on a comment, and
///    silently resolved `''`. It is now nullable and resolves `null`.
///
/// The silent-default failure mode is why every case below is an equality against a
/// **known-admin** fixture entry rather than a "decode did not throw" check — a decode
/// that defaults everything is indistinguishable from a correct one without it.
void main() {
  late List<dynamic> corpus;

  setUpAll(() {
    final file = File('test/fixtures/comment-wire-corpus.json');
    corpus = jsonDecode(file.readAsStringSync()) as List<dynamic>;
  });

  group('QA-UNIT04 -13 · Flutter comment decode', () {
    /// Green. Establishes that the fixture really is the server's five-key shape and really
    /// can express an admin flag, so a red below is the Flutter model's fault and not a
    /// broken or absent fixture.
    test('the corpus fixture is the server\'s five-key comment shape', () {
      expect(corpus.length, 2);

      final first = corpus[0] as Map<String, dynamic>;
      expect(
        first.keys.toSet(),
        {'id', 'content', 'user_id', 'is_admin', 'created_at'},
      );

      // Load-bearing: without an admin-flagged entry, the silently-defaulted `false` below
      // would be indistinguishable from a correct decode.
      expect(first['is_admin'], isTrue);
      expect((corpus[1] as Map<String, dynamic>)['is_admin'], isFalse);

      // The server sends neither of the two keys this SDK's model reads.
      expect(first.containsKey('is_team_member'), isFalse);
      expect(first.containsKey('feedback_id'), isFalse);
    });

    /// Green today. The fields Flutter reads correctly, asserted so a future regression in
    /// them is separable from the two known defects below.
    test('id, content, userId and createdAt survive the decode', () {
      final comment = Comment.fromJson(corpus[0] as Map<String, dynamic>);

      expect(comment.id, '11111111-1111-4111-8111-111111111111');
      expect(comment.content, 'Thanks for the report - this ships in 2.4.');
      expect(comment.userId, 'fixture-admin-user');
      expect(
        comment.createdAt.toUtc().toIso8601String(),
        '2023-11-14T22:13:20.000Z',
      );
    });

    test('an admin-flagged comment decodes as a team member', () {
      final admin = Comment.fromJson(corpus[0] as Map<String, dynamic>);
      final user = Comment.fromJson(corpus[1] as Map<String, dynamic>);

      expect(
        admin.isTeamMember,
        isTrue,
        reason: 'Comment.fromJson must read is_admin — the key the server actually '
            'sends. It read is_team_member until 2026-08-15, and the badge silently '
            'never rendered (QA-UNIT04-COMMENTS -13).',
      );
      // Paired positive: the non-admin entry must decode false for the *right* reason.
      // Without this, a model that hard-coded `true` would satisfy the assertion above.
      expect(user.isTeamMember, isFalse);
    });

    /// A second, independent defect, fixed with the admin flag: the server does not send
    /// `feedback_id` on a comment at all, so the field is nullable on the client and an
    /// absent key resolves `null` — never the silent `''` it shipped with.
    test('feedbackId is not silently empty', () {
      final comment = Comment.fromJson(corpus[0] as Map<String, dynamic>);

      expect(
        comment.feedbackId,
        isNot(''),
        reason: 'feedback_id is never sent on a comment; a sentinel empty string is a '
            'fabricated value (QA-UNIT04-COMMENTS -13).',
      );
      expect(
        comment.feedbackId,
        isNull,
        reason: 'The server sends no feedback_id key, so the nullable field must '
            'resolve null rather than inventing a value.',
      );
    });

    /// Non-vacuity for the whole group: `Comment.fromJson` must be capable of failing, so
    /// the greens above are a decode that ran rather than one that defaulted everything.
    test('the decode is falsifiable — a payload missing a required key throws', () {
      expect(
        () => Comment.fromJson(<String, dynamic>{'content': 'x'}),
        throwsA(anything),
      );
    });
  });
}
