import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:feedbackkit_flutter/src/models/feedback.dart';
import 'package:feedbackkit_flutter/src/models/feedback_category.dart';
import 'package:feedbackkit_flutter/src/models/feedback_status.dart';
import 'package:feedbackkit_flutter/src/models/unknown_enum_value_exception.dart';

/// `QA-UNIT05-FEEDBACK`, Flutter lane — `-04`, `-05`, `-09`, `-10`, `-11`, `-12`.
///
/// This lane carries the suite's most interesting `-05`. **Finding F6 is FIXED as of
/// 2026-08-15** (by `QA-UNIT10-SDK-PARITY`, which owns the tolerant element-drop
/// contract): until then, `feedback_status.dart` mapped every unrecognised token to
/// `FeedbackStatus.pending` and `feedback_category.dart` mapped every unrecognised token
/// to `FeedbackCategory.other` — the sentinel coercion `AGENTS.md` forbids by name in its
/// final sentence. A seventh server status rendered as *"Pending"*, `canVote` returned
/// **true** for it, and `toJson` wrote back `pending`, so the coercion was lossy on round
/// trip.
///
/// The `-05` group below was authored **pinned to that shipped defect**, precisely so its
/// fix would be a deliberate, visible red rather than a silent behaviour change. That red
/// fired when the fix landed, and the group now asserts the fixed disposition: both enums
/// throw a typed [UnknownEnumValueException], and `FeedbackApi.list` drops only the rows
/// that throw it while a genuinely malformed row still fails the decode.
///
/// The corpus in `test/fixtures/feedback-wire-corpus.json` is **not** written here. It is
/// generated by the server's `FeedbackWireContractTests` from the server's own
/// `FeedbackResponseDTO` through the server's own configured encoder, and that suite
/// byte-diffs this committed copy against a fresh regeneration.
void main() {
  /// The canon: root `CLAUDE.md`'s status partition and wire spellings.
  const wireSpellings = <FeedbackStatus, String>{
    FeedbackStatus.pending: 'pending',
    FeedbackStatus.approved: 'approved',
    FeedbackStatus.inProgress: 'in_progress',
    FeedbackStatus.testflight: 'testflight',
    FeedbackStatus.completed: 'completed',
    FeedbackStatus.rejected: 'rejected',
  };

  const terminalStatuses = <FeedbackStatus>{
    FeedbackStatus.completed,
    FeedbackStatus.rejected,
  };

  group('QA-UNIT05 -04 · Flutter wire enum', () {
    test('every status raw value is its exact wire spelling, both directions', () {
      wireSpellings.forEach((status, spelling) {
        expect(status.toJson(), spelling, reason: '$status serialises wrongly');
        expect(FeedbackStatus.fromJson(spelling), status,
            reason: '"$spelling" does not parse back to $status');
      });
      // Non-vacuity: the table covers the whole enum, and a seventh case would not be in it.
      expect(wireSpellings.length, FeedbackStatus.values.length);
    });

    test('the six wire spellings are pairwise distinct', () {
      final spellings =
          FeedbackStatus.values.map((s) => s.toJson()).toSet();
      expect(spellings.length, FeedbackStatus.values.length);
    });

    test('every category raw value is its exact wire spelling, both directions', () {
      const categorySpellings = <FeedbackCategory, String>{
        FeedbackCategory.featureRequest: 'feature_request',
        FeedbackCategory.bugReport: 'bug_report',
        FeedbackCategory.improvement: 'improvement',
        FeedbackCategory.other: 'other',
      };
      categorySpellings.forEach((category, spelling) {
        expect(category.toJson(), spelling);
        expect(FeedbackCategory.fromJson(spelling), category);
      });
      expect(categorySpellings.length, FeedbackCategory.values.length);
      expect(
        FeedbackCategory.values.map((c) => c.toJson()).toSet().length,
        FeedbackCategory.values.length,
      );
    });
  });

  group('QA-UNIT05 -10 · the 7th-status tripwire', () {
    test('FeedbackStatus has exactly six values', () {
      // A per-case table cannot detect an ADDITION — a seventh case is simply not in it.
      // Only this arithmetic can, and `testflight` was itself added after the first clients
      // shipped, so this is the shape of the change this domain actually takes.
      expect(FeedbackStatus.values.length, 6);
      expect(FeedbackCategory.values.length, 4);
    });

    test('the computed can-vote false-set is exactly {completed, rejected}', () {
      final blocked =
          FeedbackStatus.values.where((s) => !s.canVote).toSet();
      final votable = FeedbackStatus.values.where((s) => s.canVote).toSet();

      expect(blocked, terminalStatuses);
      expect(votable, {
        FeedbackStatus.pending,
        FeedbackStatus.approved,
        FeedbackStatus.inProgress,
        FeedbackStatus.testflight,
      });
      expect(blocked.length + votable.length, FeedbackStatus.values.length);
    });
  });

  group('QA-UNIT05 -09 · the can-vote truth table', () {
    // Six separate expectations rather than a spot check of the two terminal cases. Flutter's
    // predicate is a NEGATION (finding F1), and an `&&`/`||` slip in a negation flips FOUR
    // statuses at once while `completed` and `rejected` stay correct — so a two-case check
    // passes on a predicate that has stopped working entirely.
    test('pending can be voted on', () => expect(FeedbackStatus.pending.canVote, isTrue));
    test('approved can be voted on', () => expect(FeedbackStatus.approved.canVote, isTrue));
    test('inProgress can be voted on', () => expect(FeedbackStatus.inProgress.canVote, isTrue));
    test('testflight can be voted on', () => expect(FeedbackStatus.testflight.canVote, isTrue));
    test('completed cannot be voted on', () => expect(FeedbackStatus.completed.canVote, isFalse));
    test('rejected cannot be voted on', () => expect(FeedbackStatus.rejected.canVote, isFalse));
  });

  group('QA-UNIT05 -11 · cross-client partition agreement', () {
    test('the Flutter partition equals the canon every other client must also produce', () {
      // The canon written as wire tokens, which is the only vocabulary four languages share.
      // The Swift SDK, Vapor SDK, Kotlin and Flutter must all produce this same pair; the
      // Swift-side FeedbackCanVoteParityTests derives all six declarations and compares them.
      final blockedTokens =
          FeedbackStatus.values.where((s) => !s.canVote).map((s) => s.toJson()).toSet();
      expect(blockedTokens, {'completed', 'rejected'});
    });
  });

  group('QA-UNIT05 -05 · the unknown-token disposition (finding F6, FIXED 2026-08-15)', () {
    test('an unknown status token throws a typed exception, never a sentinel', () {
      // ⚠️ FLIPPED by QA-UNIT10-SDK-PARITY. This case previously PINNED the shipped
      // sentinel coercion (`fromJson('quantum') == pending`) so that its fix would be a
      // deliberate, visible red. The fix landed: the default arm now throws
      // UnknownEnumValueException, which is the seam the tolerant element-drop wrapper
      // catches per element at the list site.
      expect(
        () => FeedbackStatus.fromJson('quantum'),
        throwsA(isA<UnknownEnumValueException>()),
      );
      expect(
        () => FeedbackStatus.fromJson(''),
        throwsA(isA<UnknownEnumValueException>()),
      );
      // The Dart member spelling is not a wire token — only exact wire spellings parse.
      expect(
        () => FeedbackStatus.fromJson('inProgress'),
        throwsA(isA<UnknownEnumValueException>()),
      );
    });

    test('the thrown exception names the enum and preserves the unknown token', () {
      // The token is part of the contract: the sentinel coercion was lossy on round trip
      // (read quantum, write back pending), and a throw that discarded the token would
      // lose the same information one level up.
      try {
        FeedbackStatus.fromJson('quantum');
        fail('expected UnknownEnumValueException');
      } on UnknownEnumValueException catch (e) {
        expect(e.enumName, 'FeedbackStatus');
        expect(e.value, 'quantum');
      }
    });

    test('an unknown status can no longer become votable', () {
      // The shipped consequence of F6: fromJson('quantum') returned pending, canVote was
      // true, and the vote button stayed enabled against a status the server 403s. The
      // value cannot be constructed from an unknown token at all now.
      expect(
        () => FeedbackStatus.fromJson('quantum').canVote,
        throwsA(isA<UnknownEnumValueException>()),
      );
    });

    test('an unknown category token throws too — the fix is two enums wide, like the defect', () {
      // F6 as recorded named only `status`; feedback_category.dart carried the identical
      // `default:` sentinel arm, so both enums were fixed together.
      expect(
        () => FeedbackCategory.fromJson('quantum'),
        throwsA(isA<UnknownEnumValueException>()),
      );
      try {
        FeedbackCategory.fromJson('quantum');
        fail('expected UnknownEnumValueException');
      } on UnknownEnumValueException catch (e) {
        expect(e.enumName, 'FeedbackCategory');
        expect(e.value, 'quantum');
      }
    });

    test('a known token still parses correctly — the paired positive', () {
      // Without this the throw cases above are satisfied by a decoder that throws for
      // everything, including 'rejected'.
      expect(FeedbackStatus.fromJson('rejected'), FeedbackStatus.rejected);
      expect(FeedbackStatus.fromJson('in_progress'), FeedbackStatus.inProgress);
      expect(FeedbackCategory.fromJson('bug_report'), FeedbackCategory.bugReport);
    });
  });

  group('QA-UNIT05 -12 · the server wire corpus', () {
    late List<dynamic> corpus;

    setUp(() {
      corpus = jsonDecode(
        File('test/fixtures/feedback-wire-corpus.json').readAsStringSync(),
      ) as List<dynamic>;
    });

    test('the corpus fixture is the server shape and can express a failure', () {
      // Non-vacuity for the whole group: an emptied fixture, or one whose sparse entry had
      // quietly gained the optional keys, would leave every case below meaningless.
      expect(corpus.length, 3);
      expect((corpus[0] as Map<String, dynamic>).keys.length, 41);
      expect((corpus[0] as Map<String, dynamic>)['sync_states'], isNotNull);
      expect((corpus[2] as Map<String, dynamic>).containsKey('user_email'), isFalse);
      expect((corpus[2] as Map<String, dynamic>).containsKey('sync_states'), isFalse);
    });

    test('FeedbackItem decodes every field it declares from the server corpus', () {
      final item = FeedbackItem.fromJson(corpus[0] as Map<String, dynamic>);

      expect(item.id, '11111111-1111-4111-8111-111111111111');
      expect(item.title, 'Add a dark theme');
      expect(item.description, 'The list is hard to read at night.');
      expect(item.status, FeedbackStatus.inProgress);
      expect(item.category, FeedbackCategory.featureRequest);
      expect(item.voteCount, 7);
      expect(item.hasVoted, isTrue);
      expect(item.commentCount, 3);
      expect(item.userId, 'fixture-end-user');
      expect(item.isHiddenOverLimit, isTrue);
      expect(item.createdAt.toUtc().toIso8601String(), '2023-11-14T22:13:20.000Z');
      expect(item.updatedAt.toUtc().toIso8601String(), '2023-11-14T23:13:20.000Z');
    });

    test('the sparse corpus entry decodes with its optionals absent', () {
      final item = FeedbackItem.fromJson(corpus[2] as Map<String, dynamic>);

      expect(item.userId, 'fixture-reporter');
      expect(item.isHiddenOverLimit, isFalse);
      // Positive terminal signals rather than a green built from absences.
      expect(item.title, 'Crash on launch');
      expect(item.status, FeedbackStatus.rejected);
      expect(item.category, FeedbackCategory.other);
      expect(item.voteCount, 0);
    });

    test('all three corpus entries decode, exercising three enum arms each', () {
      final items = corpus
          .map((e) => FeedbackItem.fromJson(e as Map<String, dynamic>))
          .toList();

      expect(items.map((i) => i.status).toList(), [
        FeedbackStatus.inProgress,
        FeedbackStatus.testflight,
        FeedbackStatus.rejected,
      ]);
      expect(items.map((i) => i.category).toList(), [
        FeedbackCategory.featureRequest,
        FeedbackCategory.bugReport,
        FeedbackCategory.other,
      ]);
    });

    test('updatedAt is a REQUIRED field — a payload without it throws', () {
      // Recorded, not corrected. `FeedbackItem.updatedAt` is non-nullable and `fromJson`
      // casts `json['updatedAt'] as String` with no null guard, so a payload omitting both
      // spellings throws rather than degrading. The server does send `updated_at` on every
      // row (FluentKit touches the .update trigger on insert too), so this is latent rather
      // than live — but `FeedbackResponseDTO.updatedAt` is `Date?`, and the day a path emits
      // a row without it, every Flutter client dead-ends on the whole list.
      final withoutUpdatedAt =
          Map<String, dynamic>.from(corpus[2] as Map<String, dynamic>)
            ..remove('updated_at');
      expect(
        () => FeedbackItem.fromJson(withoutUpdatedAt),
        throwsA(isA<TypeError>()),
      );
      // The paired positive: with the key present it decodes fine.
      expect(
        FeedbackItem.fromJson(corpus[2] as Map<String, dynamic>).updatedAt,
        isA<DateTime>(),
      );
    });
  });
}
